### ISSUE TITLE
EOF in `next` should return the already parsed, valid structures

### ISSUE THREAD

**Issue by michaelbeaumont** [siderolabs/go-smbios#16]
Due to [changes in the latest LTS and thus in v1.7.6](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v6.6.39&id=50c6c51972e9561b58bc814d5953e83c3159494e) the DMI sysfs file will EOF where previously it would continue on and be decoded without error. This currently leads to errors, for example at:

https://github.com/siderolabs/go-smbios/blob/c5267640be317efd9cbbe936ab78b2a49c757edf/smbios/internal/github.com/digitalocean/go-smbios/smbios/decoder.go#L134

which with Talos manifests as:

```
controller failed {"component": "controller-runtime", "controller": "hardware.SystemInfoController", "error": "failed to decode structures: next error: error reading header: EOF"}
```

which can lead to errors decrypting partitions encrypted in v1.7.5.

I think we can do [what Linux does in this case and be lenient](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/firmware/dmi_scan.c?h=v6.6.39&id=50c6c51972e9561b58bc814d5953e83c3159494e#n97) and [just return the structures we've already parsed instead of `nil` here](https://github.com/siderolabs/go-smbios/blob/c5267640be317efd9cbbe936ab78b2a49c757edf/smbios/internal/github.com/digitalocean/go-smbios/smbios/decoder.go#L81).

**Comment by smira** [comment]
So my understanding is that DMI file which was previously not present would be present as Linux is more tolerant?
